server:
  port: 8081

spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


resilience4j:
  circuitbreaker:
    instances:
      COFFEESERVICE: # Must match the @FeignClient(name = "...")
        registerHealthIndicator: true
        slidingWindowSize: 10          # Check last 10 calls
        minimumNumberOfCalls: 5        # Start checking after 5 calls
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s    # Wait 5s before trying again
        failureRateThreshold: 50       # Open circuit if 50% fail
      PAYMENTSERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 10          # Check last 10 calls
        minimumNumberOfCalls: 5        # Start checking after 5 calls
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s    # Wait 5s before trying again
        failureRateThreshold: 50       # Open circuit if 50% fail

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

jwt:
  SECRET: ${JWT_SECRET}